#!/bin/bash

. /etc/hademo.conf

function control {
	case $1 in
		init)
			for i in 7 15 0 1 3 4 13 6; do
				wiringPi-gpio mode $i output
				wiringPi-gpio write $i 0
			done
		;;

		b)
			wiringPi-gpio write 4 1;
		;;
		nob)
			wiringPi-gpio write 4 0;
		;;
		cw)
			wiringPi-gpio write 0 0;
			wiringPi-gpio write 1 1;
		;;
		ccw)
			wiringPi-gpio write 0 1;
			wiringPi-gpio write 1 0;
		;;
		noh)
			wiringPi-gpio write 0 0;
			wiringPi-gpio write 1 0;
		;;
		up)
			wiringPi-gpio write 7 1;
			wiringPi-gpio write 15 0;
		;;
		down)
			wiringPi-gpio write 7 0;
			wiringPi-gpio write 15 1;
		;;
		nov)
			wiringPi-gpio write 7 0;
			wiringPi-gpio write 15 0;
		;;
		led)
			wiringPi-gpio write 6 1;
		;;
		noled)
			wiringPi-gpio write 6 0;
		;;

		*)
			for i in 7 15 0 1 3 4 13 6; do
				wiringPi-gpio write $i 0
			done
		;;
	esac
}

control init

while true; do
	control led
	RES=`curl -s --max-time 0.8 --fail "http://${SERVER}/cgi-bin/get_state.cgi?$CLIENT"`
	if [[ $? -ne 0 ]]; then
		control off
		for ((i=0; i<8; ++i)); do
			usleep 100000
			control	led
			usleep 100000
			control	noled
		done
		continue
	fi

	control noled
	read STATUS B V H <<< ${RES}

	if [[ "x${B}" == xbelt ]]; then
		control b
	else
		control nob
	fi
	
	if [[ "x${H}" == xcw ]]; then
		control cw
	elif [[ "x${H}" == xccw ]]; then
		control ccw
	else
		control noh
	fi

	if [[ "x${V}" == xup ]]; then
		control up
	elif [[ "x${V}" == xdown ]]; then
		control down
	else
		control nov
	fi
	
	sleep 1
done
